In [93]:
import pandas as pd

plans = pd.read_csv('plans.csv')
zips = pd.read_csv('zips.csv')

In [94]:
plans

              plan_id state   metal_level        rate  rate_area
0      74449NR9870320    GA        Silver  298.620000          7
1      26325VH2723968    FL        Silver  421.430000         60
2      09846WB8636633    IL          Gold  361.690000          5
3      78590JQ3204809    SC          Gold  379.970000          2
4      21163YD2193896    AR          Gold  359.750000          2
...               ...   ...           ...         ...        ...
22235  82645LF4472021    WI        Silver  310.740000         11
22236  07150US9925620    AZ        Silver  368.500000          2
22237  86497HD1744205    MI  Catastrophic  222.310000         15
22238  53485IP5428156    MI        Bronze  264.301321         13
22239  47011NC7752714    NJ        Silver  262.650000          1

[22240 rows x 5 columns]

In [129]:
zips.groupby(by=['zipcode', 'state']).count()

               county_code  name  rate_area
zipcode state
501     NY               1     1          1
544     NY               1     1          1
601     PR               1     1          1
602     PR               1     1          1
603     PR               1     1          1
...                    ...   ...        ...
99363   WA               1     1          1
99371   WA               1     1          1
99401   WA               1     1          1
99402   WA               1     1          1
99403   WA               2     2          2

[38943 rows x 3 columns]

In [132]:
zip_rates = pd.merge(zips, plans, on=['state','rate_area'])
# zip_rates = pd.merge(zips, plans, on=['state'])

# zips.dtypes

KeyError: False

In [133]:
foo = zip_rates[zip_rates['zipcode'].isin([50014])][zip_rates['metal_level'] == 'Silver']

/var/folders/jx/f77czcf55f5fkhqhb83tkfrh0000gn/T/ipykernel_58307/1069006860.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  foo = zip_rates[zip_rates['zipcode'].isin([50014])][zip_rates['metal_level'] == 'Silver']

In [134]:
print(len(foo[foo['rate_area'] == 1]))
print(len(foo))

10
10

In [135]:
foo.sort_values('rate',)

,zipcode,state,county_code,name,rate_area,plan_id,metal_level,rate
580891,50014,IA,19015,Boone,1,04350IN4979203,Silver,273.76
609984,50014,IA,19169,Story,1,04350IN4979203,Silver,273.76
580897,50014,IA,19015,Boone,1,29700DK6896673,Silver,287.30
609990,50014,IA,19169,Story,1,29700DK6896673,Silver,287.30
609982,50014,IA,19169,Story,1,94313WQ8579602,Silver,322.34
580889,50014,IA,19015,Boone,1,94313WQ8579602,Silver,322.34
609988,50014,IA,19169,Story,1,17607FO6892881,Silver,337.76
580895,50014,IA,19015,Boone,1,17607FO6892881,Silver,337.76
580896,50014,IA,19015,Boone,1,99015AH8158731,Silver,388.68
609989,50014,IA,19169,Story,1,99015AH8158731,Silver,388.68

In [131]:
bar = zip_rates[zip_rates['zipcode'] == 63359][zip_rates['metal_level'] == 'Silver']
bar

/var/folders/jx/f77czcf55f5fkhqhb83tkfrh0000gn/T/ipykernel_58307/2382980200.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  bar = zip_rates[zip_rates['zipcode'] == 63359][zip_rates['metal_level'] == 'Silver']

,zipcode,state,county_code,name,rate_area,plan_id,metal_level,rate
883418,63359,MO,29007,Audrain,5,92264NN0096790,Silver,361.15
883419,63359,MO,29007,Audrain,5,42632GP1338806,Silver,325.71
883423,63359,MO,29007,Audrain,5,97792GH3949680,Silver,333.99
883427,63359,MO,29007,Audrain,5,66328WW8711210,Silver,305.26
883431,63359,MO,29007,Audrain,5,30675IS8399342,Silver,363.35
883433,63359,MO,29007,Audrain,5,10537MB7049761,Silver,301.87
883434,63359,MO,29007,Audrain,5,97622EJ8546938,Silver,361.54
883436,63359,MO,29007,Audrain,5,03378BD2645512,Silver,354.77
883439,63359,MO,29007,Audrain,5,34891YG3032593,Silver,361.68
883440,63359,MO,29007,Audrain,5,82643ZC1726811,Silver,302.31
883441,63359,MO,29007,Audrain,5,01576WR8251558,Silver,305.55
883442,63359,MO,29007,Audrain,5,98991NX8275772,Silver,294.08
883445,63359,MO,29007,Audrain,5,87443IU8388368,Silver,382.79
903985,63359,MO,29113,Lincoln,6,77007VG5883053,Silver,304.42
903986,63359,MO,29113,Lincoln,6,16166AN0216191,Silver,245.30
903988,63359,MO,29113,Lincoln,6,06956CJ3239649,Silver,298.46
903990,63359,MO,29113,Lincoln,6,41235RU1831212,Silver,273.93
903991,63359,MO,29113,Lincoln,6,35329UJ6012029,Silver,284.29
903992,63359,MO,29113,Lincoln,6,58259NX3087388,Silver,281.53
903995,63359,MO,29113,Lincoln,6,88415HR2514600,Silver,304.87
903997,63359,MO,29113,Lincoln,6,72125DI2154449,Silver,287.33
903998,63359,MO,29113,Lincoln,6,66951KE0853160,Silver,295.56
904000,63359,MO,29113,Lincoln,6,01217QF6205398,Silver,297.44
904002,63359,MO,29113,Lincoln,6,13137RQ2501063,Silver,269.11
904003,63359,MO,29113,Lincoln,6,18786LD9179553,Silver,304.75
904004,63359,MO,29113,Lincoln,6,76149TC4061727,Silver,276.55
904005,63359,MO,29113,Lincoln,6,30595JF5354857,Silver,321.93
904008,63359,MO,29113,Lincoln,6,04368EL1950754,Silver,287.06
904011,63359,MO,29113,Lincoln,6,06533RV4830859,Silver,306.28
904017,63359,MO,29113,Lincoln,6,00372CZ1743381,Silver,347.36
904023,63359,MO,29113,Lincoln,6,40897NV2876122,Silver,283.96
904025,63359,MO,29113,Lincoln,6,01937JT6814958,Silver,316.79
908154,63359,MO,29139,Montgomery,5,92264NN0096790,Silver,361.15
908155,63359,MO,29139,Montgomery,5,42632GP1338806,Silver,325.71
908159,63359,MO,29139,Montgomery,5,97792GH3949680,Silver,333.99
908163,63359,MO,29139,Montgomery,5,66328WW8711210,Silver,305.26
908167,63359,MO,29139,Montgomery,5,30675IS8399342,Silver,363.35
908169,63359,MO,29139,Montgomery,5,10537MB7049761,Silver,301.87
908170,63359,MO,29139,Montgomery,5,97622EJ8546938,Silver,361.54
908172,63359,MO,29139,Montgomery,5,03378BD2645512,Silver,354.77
908175,63359,MO,29139,Montgomery,5,34891YG3032593,Silver,361.68
908176,63359,MO,29139,Montgomery,5,82643ZC1726811,Silver,302.31
908177,63359,MO,29139,Montgomery,5,01576WR8251558,Silver,305.55
908178,63359,MO,29139,Montgomery,5,98991NX8275772,Silver,294.08
908181,63359,MO,29139,Montgomery,5,87443IU8388368,Silver,382.79
912312,63359,MO,29163,Pike,2,98642CF2178853,Silver,383.71
912313,63359,MO,29163,Pike,2,97848ED6997904,Silver,443.58
912314,63359,MO,29163,Pike,2,18413ME9593743,Silver,383.86
912316,63359,MO,29163,Pike,2,39170WQ8615478,Silver,385.64
912322,63359,MO,29163,Pike,2,10095ED9559096,Silver,411.10
912324,63359,MO,29163,Pike,2,71184UR0111255,Silver,383.31
912325,63359,MO,29163,Pike,2,02222NT1714830,Silver,354.49

In [117]:
import numpy as np

def find_rate_area(zipcode):
    zipcode = zip_rates[zip_rates['zipcode'] == zipcode]
    rate_areas = zipcode['rate_area'].unique()
    if rate_areas.size == 1:
        print(rate_areas)
        return np.sort(zipcode['rate'].unique())[1]

print(find_rate_area(633359))
print(find_rate_area(50014))

None
[1]
226.57

In [104]:
import csv

In [118]:
with open('slcsp.csv') as csvfile:
    data = csv.reader(csvfile)
    next(data)
    for line in data:
        print(int(line[0]))
        find_rate_area(int(line[0]))

64148
[3]
67118
[6]
40813
18229
[3]
51012
[3]
79168
[2]
54923
67651
[4]
49448
[12]
27702
[11]
47387
[11]
50014
[1]
33608
[28]
6239
54919
[11]
46706
14846
48872
43343
77052
[10]
7734
[1]

IndexError: index 1 is out of bounds for axis 0 with size 1